use_default_settings: true

general:
  debug: false
  instance_name: "WebSearch MCP"

search:
  default_doi_resolver: "doi.org"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "put your secret key here"
  limiter: false

redis:
  url: redis://redis:6379/0
