use_default_settings: true

general:
  debug: false
  instance_name: "WebSearch MCP"

search:
  default_doi_resolver: "doi.org"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${SEARXNG_SECRET}"
  limiter: false

# Performance optimizations for API usage
outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20

# Keep only reliable engines for MCP usage
engines:
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: false
    
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    
  - name: brave
    engine: brave
    shortcut: br
    
  - name: startpage
    engine: startpage
    shortcut: sp

redis:
  url: redis://redis:6379/0
